<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.git/config</string>
		<string>.gitconfig</string>
		<string>etc/gitconfig</string>
	</array>
	<key>name</key>
	<string>Git Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#section</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>boolean</key>
		<dict>
			<key>match</key>
			<string>\b(?i:yes|no|0|1|true|false)\b</string>
			<key>name</key>
			<string>constant.language.boolean.git-config</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.git-config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.git-config</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.semi-colon.git-config</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.git-config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((#).*$\n?)|((;).*$\n?)</string>
		</dict>
		<key>section</key>
		<dict>
			<key>begin</key>
			<string>\[\s*([\w_-]+)(?:\s+((")(?:[^"\\]|\\["\\])*("))|\.([\w_-]+))?\s*\]</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.git-config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.subsection.git-config</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.subsection.begin.git-config</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.subsection.end.git-config</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.subsection.git-config</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\[)</string>
			<key>name</key>
			<string>meta.section.git-config</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value_pair</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.git-config</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.git-config</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.git-config</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[ntb"\\]</string>
					<key>name</key>
					<string>constant.character.escape.git-config</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.git-config</string>
				</dict>
			</array>
		</dict>
		<key>value_pair</key>
		<dict>
			<key>begin</key>
			<string>(\w+)\s*(=)\s*(?!$)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.git-config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.git-config</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$|(?=[#;])</string>
			<key>name</key>
			<string>meta.value-pair.section-item.git-config</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.git-config</string>
	<key>uuid</key>
	<string>F0EFAC75-4357-45BD-AB08-682DAF8C6FBF</string>
</dict>
</plist>
